apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
- ap-northeast-2a
- ap-northeast-2c

metadata:
  name: 'eks-workshop'
  region: 'ap-northeast-2'
  version: '1.25'
  tags:
    karpenter.sh/discovery: 'eks-workshop'
    created-by: eks-workshop-v2
    env: 'eks-workshop'

iam:
  withOIDC: true

vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

addons:
- name: vpc-cni
  version: v1.12.5-eksbuild.2
  configurationValues: "{\"env\":{\"ENABLE_PREFIX_DELEGATION\":\"true\", \"ENABLE_POD_ENI\":\"true\", \"POD_SECURITY_GROUP_ENFORCING_MODE\":\"standard\"}}"
  resolveConflicts: overwrite

managedNodeGroups:
- name: default
  desiredCapacity: 3
  minSize: 3
  maxSize: 6
  instanceType: t3.small
  privateNetworking: true
  releaseVersion: 1.25.6-20230304
  labels:
    workshop-default: 'yes'
